<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_taxis_rc-image-tile-33</name>
   <tag></tag>
   <elementGuidId>69308de3-8ca6-4f1d-adcc-6d72e510193c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.recaptcha.net/recaptcha/api2/payload?p=06AGdBq27OtdiblesW659aUpJ0gfgMGvz4VTXWqs95q1MBpvwOEfYEgclmeFLyrz_8HW6zkSdZW4N8PXanO5qNZu9bSkr2qiZoxy3V0mwGD37ilimuMeDZkVVA2BbzwG8QJr185DRgjYF6FgEKZDOYNQMk27hiFQk3pN1mtLeWJEhy3haQD7O8EVJlR25IfhePxfCeujhDC0YG&amp;k=6LcgI54UAAAAABGdGmruw6DdOocFpYVdjYBRe4zb</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Createprivate_space/Page_Element/iframe_httpsmatrix-client.matrix.org_c-dyz2_a63717</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.recaptcha.net/recaptcha/api2/payload?p=06AGdBq27OtdiblesW659aUpJ0gfgMGvz4VTXWqs95q1MBpvwOEfYEgclmeFLyrz_8HW6zkSdZW4N8PXanO5qNZu9bSkr2qiZoxy3V0mwGD37ilimuMeDZkVVA2BbzwG8QJr185DRgjYF6FgEKZDOYNQMk27hiFQk3pN1mtLeWJEhy3haQD7O8EVJlR25IfhePxfCeujhDC0YG&amp;k=6LcgI54UAAAAABGdGmruw6DdOocFpYVdjYBRe4zb')])[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div/div/img</value>
   </webElementXpaths>
</WebElementEntity>
